"""Phase 3.3 周报导出（Markdown）。

复用 dashboard.weekly_report endpoint 的聚合 SQL；本模块把结果渲染成
人类可读的 Markdown 文档。CLI 落盘到 reports/ 目录；admin endpoint
直接返回 text/markdown。
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Any


def render_weekly_report_markdown(payload: dict[str, Any]) -> str:
    """payload 来自 /api/v1/dashboard/weekly-report 的返回结构。"""
    days = payload.get("days", 7)
    since = payload.get("since", "")
    totals = payload.get("totals", {})
    lines: list[str] = []

    lines.append(f"# IssuePilot 周报（{days} 天）")
    lines.append("")
    lines.append(f"- 时间窗：since `{since}` → now")
    lines.append(f"- 生成时间：`{datetime.now(timezone.utc).isoformat()}`")
    lines.append("")

    # Totals
    lines.append("## 总览")
    lines.append("")
    lines.append(f"- 总 LLM 调用：**{totals.get('calls', 0)}**")
    lines.append(f"- 总成本：**${totals.get('cost_usd', 0):.4f}**")
    lines.append("")

    # Top failure modes
    modes = payload.get("top_failure_modes") or []
    lines.append("## Top 3 失败模式")
    lines.append("")
    if not modes:
        lines.append("> 该时间段无 PR 退回信号。")
    else:
        lines.append("| Category | Agent B 归因 | 次数 |")
        lines.append("|---|---|---:|")
        for m in modes[:3]:
            lines.append(
                f"| `{m.get('category')}` | {m.get('agent_b_attribution')} "
                f"| {m.get('count')} |"
            )
    lines.append("")

    # Cost by agent
    cost_by_agent = payload.get("cost_by_agent") or []
    lines.append("## 各 Agent 类型成本")
    lines.append("")
    if not cost_by_agent:
        lines.append("> 无 LLM 调用记录。")
    else:
        lines.append("| Agent | 调用 | tok in/out | $ 成本 | fallback |")
        lines.append("|---|---:|---|---:|---:|")
        for it in cost_by_agent:
            lines.append(
                f"| `{it.get('agent_kind') or '-'}` | {it.get('calls', 0)} "
                f"| {it.get('input_tokens', 0):,} / {it.get('output_tokens', 0):,} "
                f"| ${it.get('cost_usd', 0):.4f} "
                f"| {it.get('fallback_calls', 0)} |"
            )
    lines.append("")

    # Attribution
    attr = payload.get("attribution_ratio") or {}
    lines.append("## Agent B 归因比例")
    lines.append("")
    if not attr:
        lines.append("> 无 rejection_reasons 数据。")
    else:
        lines.append("| 归因 | 次数 | 占比 |")
        lines.append("|---|---:|---:|")
        for k, v in attr.items():
            lines.append(
                f"| {k} | {v.get('count', 0)} | {v.get('ratio', 0)*100:.0f}% |"
            )
    lines.append("")

    # Issue funnel
    funnel = payload.get("issue_funnel") or {}
    lines.append("## Issue 漏斗（总量）")
    lines.append("")
    non_zero = [(k, v) for k, v in funnel.items() if v]
    if not non_zero:
        lines.append("> 无 issue。")
    else:
        # 按设计顺序排序，保留 funnel 语义
        order = [
            "DISCOVERED", "ANALYZING", "PENDING_DECISION",
            "IGNORED",
            "QUEUED_DEV", "IN_DEV", "DEV_TESTING", "DEV_FAILED",
            "QUEUED_REVIEW", "IN_REVIEW", "REVIEW_REJECTED",
            "PR_SUBMITTED", "PR_MERGED", "PR_CLOSED",
            "ARCHIVED",
        ]
        ordered = sorted(non_zero, key=lambda x: order.index(x[0])
                         if x[0] in order else 999)
        lines.append("| 状态 | 数量 |")
        lines.append("|---|---:|")
        for k, v in ordered:
            lines.append(f"| `{k}` | {v} |")
    lines.append("")

    # PR outcomes
    pr_out = payload.get("pr_outcomes") or {}
    lines.append("## 本周期 PR 终态")
    lines.append("")
    if not pr_out:
        lines.append("> 无 PR 终结事件。")
    else:
        lines.append("| 终态 | 数量 |")
        lines.append("|---|---:|")
        for k, v in pr_out.items():
            lines.append(f"| `{k}` | {v} |")
    lines.append("")

    lines.append("---")
    lines.append("*generated by IssuePilot 3.3 report exporter*")
    lines.append("")
    return "\n".join(lines)
