"""1.2a core tables

Revision ID: e885fd59fd05
Revises: 2fb00d749e3d
Create Date: 2026-06-17 11:25:44.710128

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e885fd59fd05"
down_revision: Union[str, None] = "2fb00d749e3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crawl_jobs",
        sa.Column(
            "trigger",
            sa.Enum("CRON", "MANUAL_TARGET", "MANUAL_URL", name="crawl_trigger"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "RUNNING", "SUCCEEDED", "FAILED", "PARTIAL", name="crawl_status"),
            nullable=False,
        ),
        sa.Column("input_url", sa.String(length=500), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "repositories",
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("owner", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("github_id", sa.BigInteger(), nullable=True),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("primary_language", sa.String(length=50), nullable=True),
        sa.Column("languages", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("topics", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("stars", sa.Integer(), nullable=False),
        sa.Column("forks", sa.Integer(), nullable=False),
        sa.Column("open_issues_count", sa.Integer(), nullable=False),
        sa.Column("last_commit_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("merged_prs_last_30d", sa.Integer(), nullable=False),
        sa.Column("open_prs_count", sa.Integer(), nullable=False),
        sa.Column("last_crawled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("full_name"),
    )
    op.create_index(
        "ix_repositories_primary_language", "repositories", ["primary_language"], unique=False
    )
    op.create_index("ix_repositories_stars", "repositories", ["stars"], unique=False)
    op.create_table(
        "issues",
        sa.Column("repository_id", sa.UUID(), nullable=False),
        sa.Column("github_number", sa.Integer(), nullable=False),
        sa.Column("github_id", sa.BigInteger(), nullable=True),
        sa.Column("github_url", sa.String(length=500), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("labels", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("author", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DISCOVERED",
                "ANALYZING",
                "PENDING_DECISION",
                "IGNORED",
                "QUEUED_DEV",
                "IN_DEV",
                "DEV_TESTING",
                "DEV_FAILED",
                "QUEUED_REVIEW",
                "IN_REVIEW",
                "REVIEW_REJECTED",
                "PR_SUBMITTED",
                "PR_MERGED",
                "PR_CLOSED",
                "ARCHIVED",
                name="issue_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "source", sa.Enum("CRAWL", "MANUAL", "REOPEN", name="issue_source"), nullable=False
        ),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("crawl_job_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["crawl_job_id"], ["crawl_jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repository_id", "github_number", name="uq_issues_repo_number"),
    )
    op.create_index("ix_issues_repository_id", "issues", ["repository_id"], unique=False)
    op.create_index("ix_issues_source", "issues", ["source"], unique=False)
    op.create_index("ix_issues_status", "issues", ["status"], unique=False)
    op.create_table(
        "evaluations",
        sa.Column("issue_id", sa.UUID(), nullable=False),
        sa.Column("total_score", sa.Float(), nullable=False),
        sa.Column(
            "difficulty", sa.Enum("EASY", "MEDIUM", "HARD", name="issue_difficulty"), nullable=False
        ),
        sa.Column("estimated_hours", sa.Float(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=False),
        sa.Column("is_worth_developing", sa.Boolean(), nullable=False),
        sa.Column("dimensions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=20), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("is_fallback", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["issue_id"], ["issues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("issue_id"),
    )
    op.create_table(
        "llm_call_logs",
        sa.Column("issue_id", sa.UUID(), nullable=True),
        sa.Column(
            "agent_kind",
            sa.Enum(
                "AGENT_A",
                "AGENT_B",
                "AGENT_C",
                "AGENT_D",
                "REJECTION_CLASSIFIER",
                "OTHER",
                name="agent_kind",
            ),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("is_fallback", sa.Boolean(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_code", sa.String(length=50), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_creation_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("prompt_version", sa.String(length=20), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["issue_id"], ["issues.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_llm_call_logs_agent_kind", "llm_call_logs", ["agent_kind"], unique=False)
    op.create_index("ix_llm_call_logs_created_at", "llm_call_logs", ["created_at"], unique=False)
    op.create_index("ix_llm_call_logs_is_fallback", "llm_call_logs", ["is_fallback"], unique=False)
    op.create_index("ix_llm_call_logs_success", "llm_call_logs", ["success"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_llm_call_logs_success", table_name="llm_call_logs")
    op.drop_index("ix_llm_call_logs_is_fallback", table_name="llm_call_logs")
    op.drop_index("ix_llm_call_logs_created_at", table_name="llm_call_logs")
    op.drop_index("ix_llm_call_logs_agent_kind", table_name="llm_call_logs")
    op.drop_table("llm_call_logs")
    op.drop_table("evaluations")
    op.drop_index("ix_issues_status", table_name="issues")
    op.drop_index("ix_issues_source", table_name="issues")
    op.drop_index("ix_issues_repository_id", table_name="issues")
    op.drop_table("issues")
    op.drop_index("ix_repositories_stars", table_name="repositories")
    op.drop_index("ix_repositories_primary_language", table_name="repositories")
    op.drop_table("repositories")
    op.drop_table("crawl_jobs")
    # Postgres ENUM 类型不会被 drop_table 级联删除，需显式 DROP
    for enum_name in (
        "issue_status",
        "issue_source",
        "issue_difficulty",
        "crawl_trigger",
        "crawl_status",
        "agent_kind",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    # ### end Alembic commands ###
