"""1.4a dev_tasks and dev_logs

Revision ID: be207babb556
Revises: e885fd59fd05
Create Date: 2026-06-17 13:43:49.404165

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "be207babb556"
down_revision: Union[str, None] = "e885fd59fd05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dev_tasks",
        sa.Column("issue_id", sa.UUID(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "RUNNING", "SUCCEEDED", "FAILED", "TIMEOUT", name="dev_task_status"),
            nullable=False,
        ),
        sa.Column("container_id", sa.String(length=64), nullable=True),
        sa.Column("sandbox_image", sa.String(length=100), nullable=True),
        sa.Column("forked_repo", sa.String(length=255), nullable=True),
        sa.Column("branch_name", sa.String(length=200), nullable=True),
        sa.Column("workspace_path", sa.String(length=500), nullable=True),
        sa.Column("review_context", sa.Text(), nullable=True),
        sa.Column("files_changed", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("diff_summary", sa.Text(), nullable=True),
        sa.Column("failure_reason", sa.String(length=50), nullable=True),
        sa.Column("failure_detail", sa.Text(), nullable=True),
        sa.Column("test_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("loop_iterations", sa.Integer(), nullable=False),
        sa.Column("stuck_count", sa.Integer(), nullable=False),
        sa.Column("total_cost_usd", sa.Float(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["issue_id"], ["issues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_dev_tasks_issue_id", "dev_tasks", ["issue_id"], unique=False)
    op.create_index("ix_dev_tasks_status", "dev_tasks", ["status"], unique=False)
    op.create_table(
        "dev_logs",
        sa.Column("dev_task_id", sa.UUID(), nullable=False),
        sa.Column(
            "level",
            sa.Enum("DEBUG", "INFO", "WARNING", "ERROR", name="dev_log_level"),
            nullable=False,
        ),
        sa.Column(
            "step",
            sa.Enum(
                "SETUP",
                "ANALYZE",
                "PLAN",
                "IMPLEMENT",
                "TEST",
                "COMMIT",
                "SYSTEM",
                name="dev_log_step",
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["dev_task_id"], ["dev_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_dev_logs_dev_task_id", "dev_logs", ["dev_task_id"], unique=False)
    op.create_index(
        "ix_dev_logs_dev_task_id_created_at",
        "dev_logs",
        ["dev_task_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_dev_logs_dev_task_id_created_at", table_name="dev_logs")
    op.drop_index("ix_dev_logs_dev_task_id", table_name="dev_logs")
    op.drop_table("dev_logs")
    op.drop_index("ix_dev_tasks_status", table_name="dev_tasks")
    op.drop_index("ix_dev_tasks_issue_id", table_name="dev_tasks")
    op.drop_table("dev_tasks")
    # Postgres ENUM 类型不会被 drop_table 级联删除（参考 1.2a 教训）
    for enum_name in ("dev_task_status", "dev_log_level", "dev_log_step"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    # ### end Alembic commands ###
